repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  {% if cookiecutter.use_commitizen|lower == "y" -%}
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.21.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  {%- endif %}

  - repo: https://github.com/MartinThoma/check-pip-compile
    rev: 0.1.1
    hooks:
      - id: check-pip-compile
        args:
          [
            "requirements/base.in",
            "requirements/production.in",
            "requirements/development.in",
            "requirements/test.in",
          ]

  {% if cookiecutter.use_isort|lower == "y" -%}
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--filter-files"]
  {%- endif %}

  {% if cookiecutter.use_black|lower == "y" -%}
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  {%- endif %}

  {% if cookiecutter.use_flake8|lower == "y" -%}
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-simplify
        args: ["--ignore=E800,F842,F841,W503"]
  {%- endif %}

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py39]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
        stages: [commit]

  {% if cookiecutter.use_mypy|lower == "y" -%}
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        exclude: |
          (?x)^(
              docs/source/conf.py|
              cleanup.py
          )$
        additional_dependencies:
          - types-dataclasses >= 0.1.3
          - lxml
          {% if cookiecutter.command_line_interface|lower == "click" -%}
          - types-click
          {%- endif %}
  {%- endif %}

  {% if cookiecutter.use_bandit|lower == "y" -%}
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.3
    hooks:
      - id: bandit
        args:
          - -s
          - B101,B404,B603,B607
  {%- endif %}
